// Shared Goals board + detail page sample data (Figma frames 1250:8499, 1253:16470, 1256:20770).

export const GHOST_GOALS = [
  {
    id: 'ghost-goal-1',
    priority: 'URGENT',
    title: 'Fitness Regimen',
    description: 'Adhere to your workout schedule or participate in a fitness class.',
    category: 'Fitness',
    tasks: 1,
    habits: 6,
    due: 'May 21, 2026',
  },
  {
    id: 'ghost-goal-2',
    priority: 'HIGH',
    title: 'Physical Activity',
    description: 'Commit to your fitness routine or join a workout session.',
    category: 'Health',
    tasks: 4,
    habits: 2,
    due: 'In 2 days',
  },
  {
    id: 'ghost-goal-3',
    priority: 'MEDIUM',
    title: 'Improve Rate',
    description: 'Stick to your professional growth plan or engage in a skill-building session.',
    category: 'Career',
    tasks: 6,
    habits: 2,
    due: 'In 6 days',
  },
];

export const INITIAL_GOALS = [
  {
    id: 'goal-1',
    priority: 'MEDIUM',
    title: 'Improve Rate',
    description: 'Stick to your professional growth plan or engage in a skill-building session.',
    category: 'Career',
    tasks: 6,
    habits: 2,
    due: 'In 6 days',
    dueDetail: 'May 19, 2026 • In 6 days',
    progress: 70,
    status: 'active',
    source: 'ai',
  },
  {
    id: 'goal-2',
    priority: 'LOW',
    title: 'Workout',
    description: 'Stick to your exercise plan or engage in a training session.',
    category: 'Fitness',
    tasks: 0,
    habits: 1,
    due: 'May 8, 2026',
    progress: 20,
    status: 'paused',
    source: 'manual',
  },
  {
    id: 'goal-3',
    priority: 'URGENT',
    title: 'Fitness Regimen',
    description: 'Adhere to your workout schedule or participate in a fitness class.',
    category: 'Fitness',
    tasks: 1,
    habits: 6,
    due: 'May 25, 2026',
    progress: 43,
    status: 'active',
    source: 'ai',
  },
  {
    id: 'goal-4',
    priority: 'URGENT',
    title: 'Training Schedule',
    description: 'Follow your exercise routine or take part in a workout.',
    category: 'Education',
    tasks: 21,
    habits: 0,
    due: 'May 18, 2026',
    progress: 20,
    status: 'paused',
    source: 'manual',
  },
  {
    id: 'goal-5',
    priority: 'HIGH',
    title: 'Physical Activity',
    description: 'Commit to your fitness routine or join a workout session.',
    category: 'Health',
    tasks: 4,
    habits: 2,
    due: 'In 2 days',
    progress: 24,
    status: 'active',
    source: 'manual',
  },
  {
    id: 'goal-6',
    priority: 'LOW',
    title: 'Exercise Program',
    description: 'Maintain your fitness regimen or engage in a workout.',
    category: 'Health',
    tasks: 2,
    habits: 0,
    due: null,
    progress: 100,
    status: 'completed',
    completedDate: 'May 8, 2026',
    source: 'manual',
  },
  {
    id: 'goal-7',
    priority: 'LOW',
    title: 'Fitness Schedule',
    description: 'Keep up with your exercise plan or do a training session.',
    category: 'Career',
    tasks: 1,
    habits: 1,
    due: 'Today',
    progress: 7,
    status: 'active',
    source: 'manual',
  },
  {
    id: 'goal-8',
    priority: 'LOW',
    title: 'Workout Strategy',
    description: 'Stick to your fitness routine or participate in a workout.',
    category: 'Personal',
    tasks: 2,
    habits: 0,
    due: null,
    progress: 100,
    status: 'completed',
    completedDate: 'May 11, 2026',
    source: 'ai',
  },
  {
    id: 'goal-9',
    priority: 'LOW',
    title: 'Exercise Agenda',
    description: 'Follow your workout plan or engage in a fitness session.',
    category: 'Education',
    tasks: 0,
    habits: 4,
    due: 'May 27, 2026',
    progress: 89,
    status: 'active',
    source: 'ai',
  },
  {
    id: 'goal-10',
    priority: 'URGENT',
    title: 'Exercise Routine',
    description: 'Follow your fitness routine or do a workout session.',
    category: 'Career',
    tasks: 2,
    habits: 4,
    due: '04.12.26',
    progress: 70,
    status: 'active',
    source: 'ai',
  },
  {
    id: 'goal-11',
    priority: 'MEDIUM',
    title: 'Improve Rate',
    description: 'Stick to your professional growth plan or engage in a skill-building session.',
    category: 'Career',
    tasks: 2,
    habits: 4,
    due: 'In 6 days',
    progress: 70,
    status: 'active',
    source: 'ai',
  },
  {
    id: 'goal-12',
    priority: 'LOW',
    title: 'Exercise Routine',
    description: 'Follow your fitness routine or do a workout session.',
    category: 'Career',
    tasks: 2,
    habits: 4,
    due: '04.12.26',
    progress: 20,
    status: 'active',
    source: 'manual',
  },
  {
    id: 'goal-13',
    priority: 'LOW',
    title: 'Workout',
    description: 'Stick to your exercise plan or engage in a training session.',
    category: 'Fitness',
    tasks: 0,
    habits: 1,
    due: 'May 8, 2026',
    progress: 20,
    status: 'active',
    source: 'manual',
  },
  {
    id: 'goal-14',
    priority: 'LOW',
    title: 'Exercise Routine',
    description: 'Follow your fitness routine or do a workout session.',
    category: 'Career',
    tasks: 2,
    habits: 4,
    due: '04.12.26',
    progress: 100,
    status: 'completed',
    completedDate: 'May 8, 2026',
    source: 'ai',
  },
  {
    id: 'goal-15',
    priority: 'URGENT',
    title: 'Fitness Regimen',
    description: 'Adhere to your workout schedule or participate in a fitness class.',
    category: 'Fitness',
    tasks: 1,
    habits: 6,
    due: 'May 8, 2026',
    progress: 43,
    status: 'active',
    source: 'ai',
  },
];

export const FIGMA_BOARD_STATS = { active: 12, paused: 2, completedThisMonth: 3 };

// Figma frame 1256:20770 — full-page linked tasks (2×2 grid).
export const FIGMA_PAGE_TASKS = [
  {
    id: 'pt-1',
    priority: 'URGENT',
    source: 'ai',
    status: 'to do',
    statusUppercase: true,
    title: 'Exercise Routine',
    description: 'Follow your fitness routine or do a workout session.',
    tags: [
      { label: 'Career' },
      { label: 'Improve Rate', linkedGoal: true },
      { label: '60 Min', icon: 'clock' },
      { label: '0/4 Steps' },
    ],
    due: 'May 11, 2026',
    overdueDays: 2,
  },
  {
    id: 'pt-2',
    priority: 'LOW',
    status: 'In progress',
    statusUppercase: false,
    title: 'Update Resume and LinkedIn Profile',
    description:
      'Communicate the expectations regarding maintaining a calm environment to the relevant individuals in a direct and respectful manner.',
    tags: [{ label: 'Health' }, { label: '25 Min', icon: 'clock' }],
    due: 'May 13, 2026',
  },
  {
    id: 'pt-3',
    priority: 'HIGH',
    status: 'Done',
    statusUppercase: false,
    title: 'Deliver message',
    description:
      'Communicate the expectations regarding maintaining a calm environment to the relevant individuals in a direct and respectful manner.',
    tags: [{ label: 'Health' }, { label: '8/8 Steps' }],
    completedLabel: 'Completed: Yesterday',
    faded: true,
  },
  {
    id: 'pt-4',
    priority: 'MEDIUM',
    status: 'to do',
    statusUppercase: true,
    title: 'Complete Work Task',
    description: 'Work on the main career task assigned for today.',
    tags: [{ label: 'Finance' }, { label: '30 Min', icon: 'clock' }],
    due: 'Tomorrow',
    overdueLabel: 'Overdue',
    overdueOrange: true,
  },
  {
    id: 'pt-5',
    priority: 'HIGH',
    status: 'In progress',
    statusUppercase: false,
    title: 'Prepare Interview Answers',
    description: 'Review common interview questions and prepare structured responses.',
    tags: [{ label: 'Career' }, { label: '45 Min', icon: 'clock' }],
    due: 'Jun 30, 2026',
  },
  {
    id: 'pt-6',
    priority: 'LOW',
    status: 'to do',
    statusUppercase: true,
    title: 'Research Industry Trends',
    description: 'Read articles and reports on current trends in your target industry.',
    tags: [{ label: 'Career' }, { label: '20 Min', icon: 'clock' }],
    due: 'Jul 5, 2026',
  },
];

// Figma frame 1256:20770 — linked habits with Mon–Sun grid.
export const FIGMA_PAGE_HABITS = [
  {
    id: 'ph-1',
    title: 'Drink Water',
    description: 'Stay hydrated throughout the day Stay hydrated throughout the day',
    tags: [
      { label: '4 days', icon: 'flame' },
      { label: '12 days left', icon: 'hourglass' },
      { label: '+4' },
    ],
    // Frame 5.1 / Habits Drink Water: Mon empty, Tue checked, Wed 1/2, Thu+Sat hidden, Fri+Sun empty
    days: ['empty', 'checked', 'today', 'unscheduled', 'empty', 'unscheduled', 'empty'],
    todayProgress: { done: 1, total: 2 },
  },
  {
    id: 'ph-2',
    title: 'Take Breaks',
    description: 'Step away from your screen regularly',
    tags: [
      { label: '7 days', icon: 'flame', accent: true },
      { label: 'Productivity' },
      { label: '+3' },
    ],
    days: ['checked', 'checked', 'checked', 'empty', 'empty', 'empty', 'empty'],
  },
];

export const WEEKDAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

export function getGoalById(id) {
  return INITIAL_GOALS.find((g) => g.id === id) ?? null;
}

export function getPageTasks(goal) {
  if (!goal?.tasks) return [];
  return FIGMA_PAGE_TASKS.slice(0, Math.min(goal.tasks, FIGMA_PAGE_TASKS.length));
}

export function getPageHabits(goal) {
  if (!goal?.habits) return [];
  if (goal.id === 'goal-1') return FIGMA_PAGE_HABITS;
  return FIGMA_PAGE_HABITS.slice(0, Math.min(goal.habits, 2));
}
